# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By


class TestCriarusuarioGiulianaFlores():
  
  url = "https://www.giulianaflores.com.br"
  
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.driver.implicitly_wait(10)
  
  def teardown_method(self, method):
    self.driver.quit()
  
  
  def test_criarusuarioGiulianaFlores(self):
    self.driver.get(self.url)
    self.driver.set_window_size(1440, 900)
    self.driver.find_element(By.CSS_SELECTOR, "#perfil-hidden > img").click()   # Abrir Menu de Login
    self.driver.find_element(By.CSS_SELECTOR, "#UrlLogin > a").click()
    
    assert self.driver.find_element(By.CSS_SELECTOR, ".titulo-dept").text == "IDENTIFICAÇÃO" 
    
    self.driver.find_element(By.ID, "ContentSite_ibtNewCustomer").click() #criar cadastro
    
    assert self.driver.find_element(By.CSS_SELECTOR, ".titulo-dept").text == "MINHA CONTA"
    
    self.driver.find_element(By.ID, "ContentSite_txtName").click()
    self.driver.find_element(By.ID, "ContentSite_txtName").send_keys("Analu Pires")
    self.driver.find_element(By.ID, "ContentSite_txtCpf").click()
    self.driver.find_element(By.ID, "ContentSite_txtCpf").send_keys("288.939.018-70")
    self.driver.find_element(By.ID, "ContentSite_txtEmail").click()
    self.driver.find_element(By.ID, "ContentSite_txtEmail").send_keys("analu.pires@viaglam.com")
    self.driver.find_element(By.ID, "ContentSite_txtPasswordNew").click()
    self.driver.execute_script("window.scrollTo(0,55)")
    self.driver.find_element(By.ID, "ContentSite_txtPasswordNew").send_keys("QAZwsx20")
    self.driver.find_element(By.ID, "ContentSite_CustomerAddress_txtZip").click()
    self.driver.find_element(By.ID, "ContentSite_CustomerAddress_txtZip").send_keys("02870-160")
    self.driver.find_element(By.ID, "ContentSite_CustomerAddress_txtAddressNumber").click()
    self.driver.find_element(By.ID, "ContentSite_CustomerAddress_txtAddressNumber").send_keys("162")
    self.driver.find_element(By.ID, "ContentSite_CustomerAddress_txtPhoneCelularNum").click()
    self.driver.execute_script("window.scrollTo(0,838)")
    self.driver.find_element(By.ID, "ContentSite_CustomerAddress_txtPhoneCelularNum").send_keys("11981559169")
    self.driver.find_element(By.ID, "ContentSite_btnCreateCustomer").click()
    self.driver.find_element(By.ID, "perfil-display").click();